### ISSUE TITLE
Config services vs nexmo file

### ISSUE THREAD

**Issue by thoresuenert** [roomies-com/nexmo-voice-channel#1]
Hey thanks for providing this package.

What is the reason to not use the `nexmo/nexmo-laravel` config file for the from and voice config?

It feels a bit clunky to spread the configs for the same service ;)

**Comment by dwightwatson** [comment]
Hey, no worries.

A couple of reasons:

1. I don't think a package should touch on another package's config file - that's their domain, and if they decide to change things up it could interfere with this package working.

2. It matches how [Laravel's Nexmo notification channel](https://laravel.com/docs/5.8/notifications#sms-prerequisites) works, by adding the `sms_from` to `config/services.php`.

I haven't even had to publish `nexmo/nexmo-laravel`'s config file in my use - I've just made the application ID and private key available through environment variables (as shown in the readme). So my custom Nexmo configuration for `sms_from` and `call_from` only exists in `config/services.php` which doesn't seem too clunky at all.

Hope this makes sense, happy to explore in greater detail if there's room for improvement here.
